### ISSUE TITLE
Unclear sentence in the solution of readers-writers problem

### ISSUE THREAD

**Issue by javadr** [AllenDowney/LittleBookOfSemaphores#27]
In _Writer-priority readers-writers solution_ section, what do you mean precisely by  **getting obsolete data with predictable turnaround times**? 

Actually, I don't get your idea. Could you please explain it more?

> ‍‍[For some applications, it might be better to get obsolete data with predictable turnaround times.](https://github.com/AllenDowney/LittleBookOfSemaphores/blob/2d71f16952c88baa69f5dbc8dd6dc1fc9c8b4550/book/book.tex#L2546)

**Comment by AllenDowney** [comment]
If a reader proceeds while a writer is waiting, the reader won't see what that writer was going to write, so the data it reads is obsolete in that sense. But that might be better than letting a reader starve while writers come and go.

**Comment by javadr** [comment]
Thanks, that makes sense.
